galleryImages:
  - images/sourie.png
  - images/naga.gif
  - images/poisson.png
  - images/passport.png
  - images/epouvantail.jpeg
  - images/danslherbe.jpeg
  - images/moto.png
  - images/cheval.png
  - images/monstre.jpeg
  - images/velo.jpeg
  - images/corbeau.png
  - images/histoire.jpeg
  - images/bibli.jpeg
  - images/leloup.jpeg
  - images/sorciere.png
  - images/urbaine.jpeg
  - images/violon.jpeg
logo: images/logo.gif
about:
  logo: images/about.png
  text: |
    Designer packaging et produits de formation, j'ai choisi de faire de ma passion pour l’illustration mon métier. 
    J'aime créer des univers oniriques peuplés de personnages et d'animaux fantastiques. Mes illustrations, réalisées à la gouache, à l’aquarelle ou à la tablette graphique (voir les 3), sont souvent empreintes d'humour et de couleurs. 
    Mes sources d'inspiration sont mes fidèles compagnons à quatre pâte, les célébrations festives et les émotions qui nous animent au quotidien. 
    N’hésitez pas à me contacter si mon travail vous plait, je serais ravie de vous en dire plus :). 
